<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '1100d480bc155bd628f50e25376e65ee' => $baseDir . '/includes/Fuerza_add_custom_box.php',
);
