<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '1100d480bc155bd628f50e25376e65ee' => $baseDir . '/includes/Fuerza_add_custom_box.php',
    '8f0b45e9e6734bc0810b348660df8fdf' => $baseDir . '/includes/validate-action.php',
);
