<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Fuerza_add_custom_box' => $baseDir . '/includes/Fuerza_add_custom_box.php',
);
