<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit01712266640ef702fd72910c02e41343
{
    public static $prefixLengthsPsr4 = array (
        '_' => 
        array (
            '_Rede\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        '_Rede\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Fuerza_lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit01712266640ef702fd72910c02e41343::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit01712266640ef702fd72910c02e41343::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit01712266640ef702fd72910c02e41343::$classMap;

        }, null, ClassLoader::class);
    }
}
