<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4aa9859ac5fe6467a3629fe09573bac7
{
    public static $files = array (
        'b15aed4ecc754e306e7f60081789a04a' => __DIR__ . '/../../..' . '/includes/courser/Column.php',
        '5813a9ee0773dc3af3bb8e8c79bb1449' => __DIR__ . '/../../..' . '/includes/courser/Fuerza_add_custom_box.php',
        '8f0b45e9e6734bc0810b348660df8fdf' => __DIR__ . '/../../..' . '/includes/validate-action.php',
    );

    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Fuerza\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Fuerza\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Fuerza_lib',
        ),
    );

    public static $classMap = array (
        'ComposerAutoloaderInit4aa9859ac5fe6467a3629fe09573bac7' => __DIR__ . '/..' . '/composer/autoload_real.php',
        'Composer\\Autoload\\ClassLoader' => __DIR__ . '/..' . '/composer/ClassLoader.php',
        'Composer\\Autoload\\ComposerStaticInit4aa9859ac5fe6467a3629fe09573bac7' => __DIR__ . '/..' . '/composer/autoload_static.php',
        'CourseFuerza' => __DIR__ . '/../../..' . '/includes/courser/CourseFuerza.php',
        'CourseTable' => __DIR__ . '/../../..' . '/includes/courser/course_db/CourseTable.php',
        'FuerzaCursos' => __DIR__ . '/../../..' . '/includes/FuerzaCursos.php',
        'FuerzaScripts' => __DIR__ . '/../../..' . '/includes/FuerzaScripts.php',
        'FuerzaTemplate' => __DIR__ . '/../../..' . '/includes/FuerzaTemplate.php',
        'Fuerza_add_custom_box' => __DIR__ . '/../../..' . '/includes/courser/Fuerza_add_custom_box.php',
        'InsertInterested' => __DIR__ . '/../../..' . '/includes/courser/course_db/InsertInterested.php',
        'Interesting' => __DIR__ . '/../../..' . '/includes/Interesting.php',
        'haveInterested' => __DIR__ . '/../../..' . '/includes/courser/haveInterested.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4aa9859ac5fe6467a3629fe09573bac7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4aa9859ac5fe6467a3629fe09573bac7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4aa9859ac5fe6467a3629fe09573bac7::$classMap;

        }, null, ClassLoader::class);
    }
}
