<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'b15aed4ecc754e306e7f60081789a04a' => $baseDir . '/includes/courser/Column.php',
    '5813a9ee0773dc3af3bb8e8c79bb1449' => $baseDir . '/includes/courser/Fuerza_add_custom_box.php',
    '8f0b45e9e6734bc0810b348660df8fdf' => $baseDir . '/includes/validate-action.php',
);
