<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'ComposerAutoloaderInit4aa9859ac5fe6467a3629fe09573bac7' => $vendorDir . '/composer/autoload_real.php',
    'Composer\\Autoload\\ClassLoader' => $vendorDir . '/composer/ClassLoader.php',
    'Composer\\Autoload\\ComposerStaticInit4aa9859ac5fe6467a3629fe09573bac7' => $vendorDir . '/composer/autoload_static.php',
    'CourseFuerza' => $baseDir . '/includes/courser/CourseFuerza.php',
    'CourseTable' => $baseDir . '/includes/courser/course_db/CourseTable.php',
    'FuerzaCursos' => $baseDir . '/includes/FuerzaCursos.php',
    'FuerzaScripts' => $baseDir . '/includes/FuerzaScripts.php',
    'FuerzaTemplate' => $baseDir . '/includes/FuerzaTemplate.php',
    'Fuerza_add_custom_box' => $baseDir . '/includes/courser/Fuerza_add_custom_box.php',
    'InsertInterested' => $baseDir . '/includes/courser/course_db/InsertInterested.php',
    'Interesting' => $baseDir . '/includes/Interesting.php',
    'haveInterested' => $baseDir . '/includes/courser/haveInterested.php',
);
